name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  # Run daily at 1:23 UTC
  schedule:
  - cron:  '23 1 * * *'
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['2.7', '3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .[develop]

    - name: List installed dependencies
      run: python -m pip list

    - name: Run checks
      run: |
        yadage-validate madgraph_delphes.yml -t from-github/phenochain

    - name: Run unit tests
      run: |
        pytest tests
