name: publish distributions
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        type: choice
        description: 'Publish to TestPyPI?'
        options:
        - false
        - true

jobs:
  build-and-publish:
    name: Build and publish Python distro to (Test)PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install python-build, check-manifest, and twine
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install build check-manifest twine
        python -m pip list

    - name: Check MANIFEST
      run: |
        check-manifest

    - name: Build a sdist and a wheel
      run: |
        python -m build .

    - name: Verify the distribution
      run: twine check dist/*

    - name: List contents of sdist
      run: python -m tarfile --list dist/yadage-schemas-*.tar.gz

    - name: List contents of wheel
      run: python -m zipfile --list dist/yadage_schemas-*.whl

    - name: Publish distribution 📦 to Test PyPI
      # Publish to TestPyPI on tag events of if manually triggered
      # Compare to 'true' string as booleans get turned into strings in the console
      if: >-
        (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.repository == 'yadage/yadage-schemas')
        || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true' && github.repository == 'yadage/yadage-schemas')
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        password: ${{ secrets.test_pypi_api_token }}
        repository_url: https://test.pypi.org/legacy/
        print_hash: true

    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'release' && github.event.action == 'published' && github.repository == 'yadage/yadage-schemas'
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        password: ${{ secrets.pypi_api_token }}
        print_hash: true
